### ISSUE TITLE
게시글 조회시 방문 횟수 오류

### ISSUE THREAD

**Issue by mini0192** [mini0192/TeamBack#7]
게시글 조회 시 개별 게시글을 조회하게 되면 count는 올라가는 것으로 확인이 되었는데 DB에서는 카운트가 안올라 가는 오류가 있습니다!
그래서 게시글 전체 조회 시 모든 게시글의 조회수가 0으로 표시가 됩니다!

이거에 대한 해결 방안 생각하시는 거 있으신가요?

```
개별 게시글 조회 응답
{
    "locationName": "string",
    "formattedAddress": "string",
    "latitude": "string",
    "longitude": "string",
    "title": "string",
    "Body": "string",
    "view": 12,
    "satisfaction": 0,
    "memberNickname": "소인국갔다옴",
    "boardScore": {
        "size": 1,
        "userIdList": [
            1
        ],
        "avgScore": 5
    }
}
```
```
모든 게시글 조회 응답
{
    "content": [
        {
            "id": 1,
            "locationName": "string",
            "formattedAddress": "string",
            "latitude": "string",
            "longitude": "string",
            "title": "string",
            "view": 0,
            "satisfaction": 0,
            "memberNickname": "소인국갔다옴"
        }
    ],
    ...내용
}
```

**Comment by Go-EunLee** [comment]
전체 게시글 목록에서만 제대로 반영이 안되고 개별 게시글에서는 반영이 되는 건가요?? 아니면 다른 페이지를 가면 view 가 아예 초기화 되어 버리는 건가요??

**Comment by mini0192** [comment]
> 전체 게시글 목록에서만 제대로 반영이 안되고 개별 게시글에서는 반영이 되는 건가요?? 아니면 다른 페이지를 가면 view 가 아예 초기화 되어 버리는 건가요??

데이터베이스 연동을 해서 확인해 본 결과 개별 게시글 확인에 있어서 DB에는 변화가 없지만 값이 올라가더라고요 아마 Redis 설정 때문인 것 같아요! 그래서 개별 게시글에 있어서 조회수가 계속 올라가지만 DB에는 변화가 없어 전체 게시글 조회 시 DB에 저장된 0을 계속 반환하는 거 같습니다

**Comment by Go-EunLee** [comment]
아니면 view 를 올리고 save 를 하는데 이걸 삭제해보고 한 번 해봐주실 수 있나요??

**Comment by mini0192** [comment]
> 아니면 view 를 올리고 save 를 하는데 이걸 삭제해보고 한 번 해봐주실 수 있나요??

한번 시도해보고 다시 말씀드릴게요!

**Comment by mini0192** [comment]
> 아니면 view 를 올리고 save 를 하는데 이걸 삭제해보고 한 번 해봐주실 수 있나요?? 74번째 줄이요!

board.addViewCount() 함수가 redis에서 받아온 값을 저장하고 있는데 제가 수정하면 꼬일 것 같아서 혹시 이 부분 수정해주실 수 있으신가요?
